include $(GOROOT)/src/Make.$(GOARCH)
 
TARG=graph
GOFILES=               \
	graph.go           \
	DirectedMap.go     \
	UndirectedMatrix.go\
	UndirectedMap.go   \
	ConnectionsIterators.go
 
include $(GOROOT)/src/Make.pkg
