include $(GOROOT)/src/Make.$(GOARCH)
 
TARG=graph
GOFILES=               \
	graph.go           \
	search.go          \
	filters.go         \
	algorithms.go      \
	stuff.go           \
	output.go          \
	input.go           \
	comparators.go     \
	DirectedMap.go     \
	UndirectedMatrix.go\
	UndirectedMap.go   \
	MixedMatrix.go     \
	MixedMap.go        \
	neighbours_extractor.go \
	iterators.go
 
include $(GOROOT)/src/Make.pkg
