include $(GOROOT)/src/Make.$(GOARCH)
 
TARG=graph
GOFILES=                    \
	algorithms.go           \
	comparators.go          \
	DirectedMap.go          \
	filters.go              \
	graph.go                \
	input.go                \
	iterators.go            \
	MixedMap.go             \
	MixedMatrix.go          \
	neighbours_extractor.go \
	output.go               \
	search.go               \
	stuff.go                \
	UndirectedMap.go        \
	UndirectedMatrix.go
 
include $(GOROOT)/src/Make.pkg
